production:
  adapter: postgresql
  database: gptp
  pool: 5
  timeout: 5000
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost

test:
  adapter: postgresql
  database: new-test.db
  pool: 5
  timeout: 5000

